name: blueearth-cst

channels:
  - conda-forge
  - r

# notes R packages stats and utils were not found
dependencies:
  - affine
  - click
  - black
  - bottleneck
  - cartopy # to run examples
  - dask
  - datrie # for snakemake
  - dvc
  - descartes
  - entrypoints
  - flit>=3.2
  - gdal>=3.1
  - geopandas
  - git
  - graphviz
#  - hydromt>=0.4.3
#  - hydromt_wflow>=0.1.3
  - jupyter # to run examples
  - netcdf4
  - matplotlib # to run examples
  - numba
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyflwdir>=0.5.0
  - pygeos>=0.8
  - python>=3.7
  - rasterio
  - r-base
  - r-essentials
  - r-akima
  - r-patchwork
  - r-doparallel
  - r-devtools
  - r-dplyr
  - r-e1071
  - r-fitdistrplus
  - r-forecast
  - r-ggplot2
  - r-MASS
  - r-ncdf4
#  - r-rlang
  - r-scales
  - r-sf
  - r-tibble
  - r-tidyr
  - r-r.utils
  - r-yaml
  - rpy2
  - rtools
  - requests
  - scipy
  - toml
  - xarray
  - zarr
  - pip:
    - git+https://github.com/Deltares/hydromt.git
    - git+https://github.com/Deltares/hydromt_wflow.git
    - hydroengine
    - snakemake
