name: blueearth-cst

channels:
  - conda-forge

dependencies:
  - affine
  - click
  - black
  - bottleneck
  - cartopy # to run examples
  - dask
  - datrie # for snakemake
  - dvc
  - entrypoints
  - flit>=3.2
  - gdal>=3.1
  - geopandas
  - hydromt>=0.4.3
  - hydromt_wflow>=0.1.3
  - jupyter # to run examples
  - netcdf4
  - matplotlib # to run examples
  - numba
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyflwdir>=0.5.0
  - pygeos>=0.8
  - python>=3.7
  - rasterio
  - r-base
  - r-essentials
  - rpy2
  - requests
  - scipy
  - toml
  - xarray
  - zarr
  - pip:
    - hydroengine
    - snakemake
