[project]
channels = ["conda-forge", "r", "bioconda", "pip"]
description = "Add a short description here"
name = "cst"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[system-requirements]
linux = "4.18"

[tasks]

[dependencies]
cartopy = "*"
configargparse = "1.7"
datrie = "*"
dvc = "*"
descartes = "*"
flit = ">=3.2"
gcsfs = ">=2023.12.1"
gdal = ">=3.1"
geopandas = ">=0.10"
graphviz = "*"
hydromt = ">=0.9.4"
hydromt_wflow = ">=0.6.0"
jupyter = "*"
matplotlib = "*"
numpy = "*"
pandas = ">=2.0.0"
pip = "*"
python = ">=3.9,<3.12"
r-base = "*"
r-essentials = "*"
r-akima = "*"
r-patchwork = "*"
r-doparallel = "*"
r-devtools = "*"
r-dplyr = "*"
r-e1071 = "*"
r-fitdistrplus = "*"
r-forecast = "*"
r-ggplot2 = "*"
r-mass = "*"
r-ncdf4 = "*"
r-scales = "*"
r-sf = "*"
r-tibble = "*"
r-tidyr = "*"
"r-r.utils" = "*"
r-yaml = "*"
rpy2 = "*"
scipy = "*"
seaborn = "*"
shapely = ">=2.0.0"
tabulate = "==0.8.10"
xarray = "<=2024.3.0"
xclim = "*"
zarr = "*"
plotly = ">=5.24.1,<6"
snakemake-executor-plugin-cluster-generic = ">=1.0.9,<2"
icecream = ">=2.1.3,<3"
rich = ">=13.9.4,<14"

[target.win-64.dependencies]
rtools = "*"
configargparse = ">=1.7,<2"

[target.win-64.pypi-dependencies]
configargparse = "*"

[pypi-dependencies]
hydroengine = "*"
gwwapi = "*"
snakemake = "*"
