"""Two-layer tests for the interchange-contract validators (design §5.5).

- **Layer 1 — synthetic pass/fail, fixture-independent, ALWAYS executed.**
  Every validator ships a conforming in-memory object (report == []) and a
  deliberately broken one (report != []). No file I/O — objects are built
  directly here (the validators take parsed objects, never paths), so a
  fixtureless checkout (fresh clone, CI) still executes every validator's pass
  AND fail path. "Green" is never indistinguishable from "nothing checked".

- **Layer 2 — real-fixture integration, skipped VISIBLY when the fixture is
  absent.** Each case opens an artifact under the untracked ``test_case/test_local``
  tree and carries the repo fixture-absent guard (mirroring
  ``tests/test_store_region_bbox.py``): a module-level ``_FIXTURE_ABSENT``
  reason constant + ``@pytest.mark.skipif``. Absence is a NAMED, reported
  condition (read via ``pytest -rs``), never silence. The three temp() content
  validators (WG-4/WG-6/HM-6b) additionally skip with a documented reason when
  the temp artifact is absent (the default fixture state) — see the commit-4
  temp layer.

Source of record: ``dev/milestones/p32b/interchange-contracts-design.md`` §5.5 and the two
seam docs ``dev/reference/contracts/*-seam.md``.
"""
import os
from os.path import dirname, join, realpath

import pandas as pd
import pytest
import yaml

from blueearth_cst.shared import interchange_contracts as ic  # noqa: E402
from blueearth_cst.shared.snake_utils import stress_test_grid  # noqa: E402

# --- Fixture location + the single named skip reason -----------------------

TESTDIR = dirname(realpath(__file__))
SNAKEDIR = join(TESTDIR, "..")
_FIXTURE = join(SNAKEDIR, "test_case", "test_local")
_EXP = join(_FIXTURE, "experiments", "experiment")

# Fixture sub-roots, named after the Snakefile path variables they mirror so a
# future tree move has ONE place to change here instead of a dozen literals.
#
#   _MODEL_DIR  <- basin_dir  = {project_dir}/models/hydrology/wflow
#   _STORE_ROOT <- store_dir  = {project_dir}/data/climate/historical/<key>
#   _WG_DIR     <- wg_dir     = {exp_dir}/climate/weathergenr
#   _RUNS_DIR   <- runs_dir   = {exp_dir}/hydrology/wflow
#
# R9 P2 moved every one of these and this file was NOT re-pointed. The staleness
# survived because the whole Layer-2 block is `skipif(not _fixture_present())`
# and the fixture is untracked: it is absent in every worktree and on CI, so 22
# dead paths sat green everywhere until the first post-R9 `pytest tests/` in the
# primary checkout (2026-08-05, 22 FileNotFoundError). R9's own gates --
# `semantic_tree_diff` and `check_baseline` -- validate the tree's SHAPE, not the
# code that reads it, so neither could have caught this. Keeping the roots here,
# derived and commented, is what makes the next move a one-line edit.
_MODEL_DIR = join(_FIXTURE, "models", "hydrology", "wflow")
_STORE_ROOT = join(_FIXTURE, "data", "climate", "historical")
_WG_DIR = join(_EXP, "climate", "weathergenr")
_RUNS_DIR = join(_EXP, "hydrology", "wflow")
# The generated climate catalog joins the experiment's own config dir (R9
# arch-10), it is not loose at the experiment root.
_EXP_CATALOG = join(_EXP, "config", "catalogs", "data_catalog_climate_experiment.yml")

_FIXTURE_ABSENT = (
    "untracked test_case/test_local fixture tree not present "
    "(interchange-contract integration layer skipped)"
)


def _fixture_present() -> bool:
    return os.path.exists(_FIXTURE)


# --- the pre-P2 member-token guard -----------------------------------------
#
# R11 P2 renamed the member token `cst_` -> `st_` in filenames and catalog
# keys. The fixture is only regenerated when WF3 re-runs, which P2 does not do
# -- P3 owns the single re-run and re-record -- so it still carries `cst_`
# names. The Layer-2 cases below therefore assert the POST-rename path and skip
# on the SPECIFIC pre-rename shape: the old-token twin present exactly where
# the new-token artifact is missing. Never a bare existence guard, which is how
# R9-4 turned a wrong path into a silent pass (AGENTS.md); if NEITHER exists the
# helper returns the new path and the caller fails loudly, as it should.
_PRE_P2_MEMBER_TOKEN = (
    "fixture still carries the pre-P2 `cst_` member token; "
    "regenerated by P3's WF3 re-run"
)


def _member_artifact(new_path: str, legacy_path: str) -> str:
    """``new_path``, or skip iff only its pre-P2 ``cst_`` twin is on disk."""
    if not os.path.exists(new_path) and os.path.exists(legacy_path):
        pytest.skip(_PRE_P2_MEMBER_TOKEN)
    return new_path


# ===========================================================================
# Layer 1 — synthetic pass/fail (fixture-independent, always executed)
# ===========================================================================
#
# Objects are built with xarray/pandas in-memory. Each validator gets one
# conforming object (report == []) and one one-fault object (report != []).


def _wg1_good():
    import numpy as np
    import xarray as xr

    n = 3
    ds = xr.Dataset(
        {
            v: (
                ("time", "latitude", "longitude"),
                np.zeros((n, 2, 2), dtype="float32"),
                {"units": u},
            )
            for v, u in ic._WG1_VARS_UNITS.items()
        },
        coords={
            "time": pd.date_range("2000-01-01", periods=n),
            "latitude": np.array([1.0, 2.0], dtype="float32"),
            "longitude": np.array([1.0, 2.0], dtype="float32"),
            "spatial_ref": 0,
        },
        attrs={"crs": 4326, "category": "meteo"},
    )
    return ds


def test_wg1_synthetic_pass():
    assert ic.validate_wg1(_wg1_good()) == []


def test_wg1_synthetic_fail():
    ds = _wg1_good().drop_vars("precip")  # missing a pinned variable
    assert ic.validate_wg1(ds) != []


def _wg2_good():
    return pd.DataFrame(
        {
            "month": list(range(1, 13)),
            "temp_mean": [0.0] * 12,
            "precip_mean": [0.7] * 12,
            "precip_variance": [1.0] * 12,
        }
    )


def test_wg2_synthetic_pass():
    assert ic.validate_wg2(_wg2_good()) == []


def test_wg2_synthetic_fail():
    df = _wg2_good().iloc[:6]  # only 6 rows, month domain broken
    assert ic.validate_wg2(df) != []


def _wg3_good():
    return {
        "general": {"variables": ["precip", "temp"]},
        "generateWeatherSeries": {k: 0 for k in ic._WG3_GWS_KEYS},
        # C29 moved these here from the retired per-member config.
        "temp": {"transient_change": True},
        "precip": {"transient_change": True},
    }


def test_wg3_synthetic_pass():
    assert ic.validate_wg3(_wg3_good()) == []


def test_wg3_synthetic_fail():
    cfg = _wg3_good()
    del cfg["generateWeatherSeries"]["seed"]  # a required key removed
    assert ic.validate_wg3(cfg) != []


@pytest.mark.parametrize("section", ["temp", "precip"])
def test_wg3_requires_the_transient_flags(section):
    """C29: the shared config is now the ONLY carrier of these two flags.

    Rule 3.05 used to supply them per member. With that rule gone, an omission
    here reaches `impose_climate_change.R` as NULL and the perturbation silently
    takes whatever weathergenr defaults to -- so the contract has to pin them.
    """
    cfg = _wg3_good()
    del cfg[section]["transient_change"]
    diffs = ic.validate_wg3(cfg)
    assert diffs and any(f"{section}.transient_change" in d for d in diffs)


def _catalog_entry_good(uri="X:/rlz.nc"):
    return {
        "uri": uri,
        "driver": {
            "name": "raster_xarray",
            "options": {"preprocess": "harmonise_dims", "lock": False},
        },
        "metadata": {"crs": 4326, "category": "meteo"},
        "data_type": "RasterDataset",
    }


def _wg5_good(keys=("rlz_1_st_0", "rlz_1_st_1")):
    return {k: _catalog_entry_good() for k in keys}


def test_wg5_synthetic_pass():
    assert ic.validate_wg5(_wg5_good()) == []


def test_wg5_synthetic_fail():
    cfg = _wg5_good()
    cfg["rlz_1_st_1"]["driver"]["name"] = "wrong_driver"  # bad driver
    assert ic.validate_wg5(cfg) != []


def _hm1_good():
    import numpy as np
    import xarray as xr

    return xr.Dataset(
        {v: (("latitude", "longitude"), np.zeros((2, 2))) for v in ic._HM1_REFERENCED},
        coords={
            "latitude": np.array([1.0, 2.0], dtype="float64"),
            "longitude": np.array([1.0, 2.0], dtype="float64"),
            "spatial_ref": 0,
        },
    )


def test_hm1_synthetic_pass():
    assert ic.validate_hm1(_hm1_good()) == []


def test_hm1_synthetic_fail():
    ds = _hm1_good().drop_vars("outlets")  # a referenced name missing
    assert ic.validate_hm1(ds) != []


def _hm2_good():
    import numpy as np
    import xarray as xr

    n = 3
    ds = xr.Dataset(
        {
            "precip": (
                ("time", "latitude", "longitude"),
                np.zeros((n, 2, 2), dtype="float32"),
                {"units": "mm d**-1", "unit": "mm", "grid_mapping": "spatial_ref"},
            ),
            # pet: unit attr ABSENT on purpose — proves asserted-if-present
            # never blocks when the attr is missing.
            "pet": (
                ("time", "latitude", "longitude"),
                np.zeros((n, 2, 2), dtype="float32"),
                {"grid_mapping": "spatial_ref"},
            ),
            "temp": (
                ("time", "latitude", "longitude"),
                np.zeros((n, 2, 2), dtype="float32"),
                {"unit": "degree C.", "grid_mapping": "spatial_ref"},
            ),
        },
        coords={
            "time": pd.date_range("2000-01-01", periods=n),
            "latitude": np.array([1.0, 2.0], dtype="float64"),
            "longitude": np.array([1.0, 2.0], dtype="float64"),
            "spatial_ref": 0,
        },
    )
    return ds


def test_hm2_synthetic_pass():
    # A present-but-correct unit (precip) + an absent unit (pet) both pass.
    assert ic.validate_hm2(_hm2_good()) == []


def test_hm2_synthetic_fail():
    ds = _hm2_good()
    ds["temp"].attrs["unit"] = "kelvin"  # present-but-wrong unit attr
    assert ic.validate_hm2(ds) != []


def _hm3_good():
    import geopandas as gpd
    from shapely.geometry import Point, Polygon

    region = gpd.GeoDataFrame(
        {"geometry": [Polygon([(0, 0), (1, 0), (1, 1), (0, 1)])]}, crs="EPSG:4326"
    )
    outlets = gpd.GeoDataFrame({"geometry": [Point(0.5, 0.5)]}, crs="EPSG:4326")
    outlet_index = pd.DataFrame(
        {"station_name": ["a"], "subcatchment_id": [1], "x": [0.5], "y": [0.5]}
    )
    return region, outlets, outlet_index


def test_hm3_synthetic_pass():
    assert ic.validate_hm3(*_hm3_good()) == []


def test_hm3_synthetic_fail():
    region, outlets, outlet_index = _hm3_good()
    region = region.to_crs("EPSG:3857")  # wrong CRS
    assert ic.validate_hm3(region, outlets, outlet_index) != []


def _hm4_good():
    return {
        "dir_output": ".",
        "model": {"cold_start__flag": True},
        "time": {
            "calendar": "standard",
            "starttime": "2070-01-01T00:00:00",
            "endtime": "2090-12-31T00:00:00",
            "timestepsecs": 86400,
        },
        "state": {"path_input": "in.nc", "path_output": "out.nc"},
        "input": {
            "path_static": "staticmaps.nc",
            "path_forcing": "inmaps.nc",
            "forcing": {
                "atmosphere_water__precipitation_volume_flux": "precip",
                "land_surface_water__potential_evaporation_volume_flux": "pet",
                "atmosphere_air__temperature": "temp",
            },
        },
        "output": {
            "csv": {
                "path": "output.csv",
                "column": [{"header": "Q", "map": "outlets", "parameter": "q"}],
            }
        },
    }


def test_hm4_synthetic_pass():
    assert ic.validate_hm4(_hm4_good()) == []


def test_hm4_synthetic_fail():
    cfg = _hm4_good()
    del cfg["time"]["timestepsecs"]  # a pinned rewrite field missing
    assert ic.validate_hm4(cfg) != []


def _hm5_good():
    return pd.DataFrame({"time": ["2070-01-01"], "Q_130000086": [1.0]})


def test_hm5_synthetic_pass():
    assert ic.validate_hm5(_hm5_good()) == []


def test_hm5_synthetic_fail():
    df = pd.DataFrame({"Q_130000086": [1.0]})  # no time column
    assert ic.validate_hm5(df) != []


def _hm7_row(metric, rlz, location="101", temp=0.0, precip=0.0, value=1.0,
             st_id="0"):
    return {
        "metric": metric, "st_id": st_id,
        "temp_change": temp, "precip_change": precip,
        "realization_id": rlz, "location": location, "value": value,
    }


def _design(rows=((("0"), 0.0, 0.0),)):
    """A stress_test_design.csv as rule 3.09 writes it."""
    return pd.DataFrame(
        [{"st_id": s, "temp_change": t, "precip_change": p} for s, t, p in rows]
    )


def _hm7_good():
    """A minimal long table: one class-A metric per realization, one pooled."""
    rows = [_hm7_row("q_annual_mean", r) for r in (1, 2)]
    rows.append(_hm7_row("q_return_level_10yr_max", 0))
    return {"q": pd.DataFrame(rows)}


def test_hm7_synthetic_pass():
    assert ic.validate_hm7(_hm7_good(), rlz_num=2) == []


def test_hm7_synthetic_fail():
    tables = _hm7_good()
    tables["q"] = tables["q"].rename(columns={"location": "gauge"})
    assert ic.validate_hm7(tables, rlz_num=2) != []


def test_hm7_pins_the_header_exactly_now_that_it_cannot_vary():
    """The pre-R11 validator had to widen to a MEMBERSHIP test because the wide
    header grew with the gauge count and the configured basavg variables. The
    long shape is fixed, so the exact assertion is available again -- and an
    extra column is a violation rather than something to tolerate."""
    tables = _hm7_good()
    tables["q"]["wind_change"] = 1.0  # an eighth column is a violation, not tolerated
    diffs = ic.validate_hm7(tables, rlz_num=2)
    assert diffs and "expected exactly" in diffs[0]


def test_hm7_rejects_a_metric_that_disagrees_with_its_own_table():
    """The composite carries the variable, so no `variable` column exists. That
    redundancy is safe only because this is asserted."""
    tables = {"aet": pd.DataFrame([_hm7_row("q_annual_mean", 1, location="basin")])}
    diffs = ic.validate_hm7(tables, rlz_num=1)
    assert diffs and "do not begin with" in diffs[0]


def test_hm7_matches_the_vocabulary_as_a_pattern_not_an_enumeration():
    """Tpeak/Tlow are config values interpolated into two metric names, so an
    enumerated check would reject every project whose return periods differ from
    the fixture's -- the same fixture-shaped defect the wide validator had."""
    rows = [_hm7_row("q_return_level_50yr_max", 0), _hm7_row("q_annual_mean", 1)]
    assert ic.validate_hm7({"q": pd.DataFrame(rows)}, rlz_num=1) == []


def test_hm7_rejects_an_unrecognised_metric():
    """Widening to a pattern must not become 'accept anything'."""
    rows = [_hm7_row("q_totally_made_up", 1)]
    diffs = ic.validate_hm7({"q": pd.DataFrame(rows)}, rlz_num=1)
    assert diffs and "unrecognised metric" in diffs[0]


def test_hm7_enforces_the_grain_invariant():
    """`realization_id = 0` is a numeric sentinel in a numeric key column. It is
    safe ONLY because no metric emits both grains -- otherwise a
    `groupby('realization_id')` folds pooled rows in as another realization.
    Since 0 cannot announce itself, the validator asserts it."""
    pooled_as_member = [_hm7_row("q_return_level_10yr_max", 1)]
    diffs = ic.validate_hm7({"q": pd.DataFrame(pooled_as_member)}, rlz_num=2)
    assert diffs and "pooled-only" in diffs[0]

    member_as_pooled = [_hm7_row("q_annual_mean", 0)]
    diffs = ic.validate_hm7({"q": pd.DataFrame(member_as_pooled)}, rlz_num=2)
    assert diffs and "per-realization" in diffs[0]


def test_hm7_rejects_a_realization_id_outside_the_declared_range():
    rows = [_hm7_row("q_annual_mean", 7)]
    diffs = ic.validate_hm7({"q": pd.DataFrame(rows)}, rlz_num=2)
    assert diffs and "outside" in diffs[0]


def test_hm7_rejects_the_pre_r11_wide_header():
    """The reshape is a contract change, so the OLD header must now FAIL.

    A stale writer still emitting `statistic,temp_change,precip_change,Q_<id>`
    would otherwise go undetected, which is exactly what the migration record
    exists to prevent -- so this pins the rejection, not only the acceptance.
    """
    wide = pd.DataFrame(
        columns=["statistic", "temp_change", "precip_change", "Q_130000086"]
    )
    diffs = ic.validate_hm7({"q": wide}, rlz_num=2)
    assert diffs and "expected exactly" in diffs[0]


# --- Relational synthetic pass/fail (break exactly ONE member) -------------


def _gauge_identity_good():
    toml_cfg = {
        "output": {
            "csv": {
                "path": "output.csv",
                "column": [{"header": "Q", "map": "outlets", "parameter": "q"}],
            }
        }
    }
    output_rlz = pd.DataFrame({"time": ["2070-01-01"], "Q_130000086": [1.0]})
    # R11 CR-2: locations are ROWS now, so check 3 compares the `location` value
    # set rather than subtracting non-gauge columns out of a wide header.
    qstats = pd.DataFrame([_hm7_row("q_annual_mean", 1, location="130000086")])
    return toml_cfg, output_rlz, qstats


def test_gauge_identity_synthetic_pass():
    assert ic.validate_hm_gauge_column_identity(*_gauge_identity_good()) == []


def test_gauge_identity_synthetic_fail():
    toml_cfg, output_rlz, qstats = _gauge_identity_good()
    # Break exactly ONE member of the correlated set: change the q table's
    # location so check 3 fires while TOML + output_rlz still agree.
    qstats = pd.DataFrame([_hm7_row("q_annual_mean", 1, location="999999999")])
    assert ic.validate_hm_gauge_column_identity(toml_cfg, output_rlz, qstats) != []


# --- C28: st_id and the cached-copy consistency check ------------------------


def test_hm7_accepts_a_table_that_agrees_with_the_design_table():
    tables = _hm7_good()
    assert ic.validate_hm7(tables, rlz_num=2, design=_design()) == []


def test_hm7_reports_an_axis_column_that_drifted_from_the_design_table():
    """C28's whole reason: the axis columns are a CACHED COPY of a design row.

    The writer derives them independently, from the parameter files, so they
    really can disagree -- perturb one and the check must say so, naming the
    st_id and the column. A copy nothing verifies is a copy that eventually
    lies.
    """
    tables = _hm7_good()
    tables["q"].loc[0, "temp_change"] = 2.5  # design says 0.0
    diffs = ic.validate_hm7(tables, rlz_num=2, design=_design())
    assert diffs and "temp_change" in diffs[0] and "drifted" in diffs[0]


def test_hm7_reports_an_st_id_the_design_table_does_not_define():
    """A results row for a member that is not in the design is unjoinable."""
    tables = _hm7_good()
    tables["q"].loc[0, "st_id"] = "07"
    diffs = ic.validate_hm7(tables, rlz_num=2, design=_design())
    assert diffs and "does not define" in diffs[0]


def test_hm7_skips_the_c28_check_when_no_design_table_is_supplied():
    """Skipped, never silently passed: a caller with only the tables can still
    assert the header, the vocabulary and the grain."""
    assert ic.validate_hm7(_hm7_good(), rlz_num=2) == []
    broken = _hm7_good()
    broken["q"].loc[0, "temp_change"] = 2.5
    assert ic.validate_hm7(broken, rlz_num=2) == []  # unchecked without a design


def _catalog_grid_good():
    keys = [f"rlz_{n}_st_{m}" for n in (1, 2) for m in range(0, 7)]
    catalog = {k: _catalog_entry_good() for k in keys}
    return catalog, 2, 6  # rlz_num=2, st_num=6


def test_catalog_grid_synthetic_pass():
    catalog, rlz_num, st_num = _catalog_grid_good()
    assert ic.validate_wg5_catalog_grid(catalog, rlz_num, st_num) == []


def test_catalog_grid_synthetic_fail():
    catalog, rlz_num, st_num = _catalog_grid_good()
    # Break exactly ONE member: drop a single expected catalog key.
    del catalog["rlz_1_st_0"]
    assert ic.validate_wg5_catalog_grid(catalog, rlz_num, st_num) != []


# --- temp() content validators — synthetic pass/fail (commit-4 layer) -------
#
# WG-4 / WG-6 / HM-6b real artifacts are temp()-deleted and absent on the
# fixture; only their on-disk integration checks are skip-until-captured. Their
# logic is proven here on every checkout, fixture-independently.


def _wg4_good():
    import numpy as np
    import xarray as xr

    n = 3
    return xr.Dataset(
        {
            "precip": (("time", "lat", "lon"), np.zeros((n, 2, 2), dtype="float32")),
            "temp": (("time", "lat", "lon"), np.zeros((n, 2, 2), dtype="float32")),
        },
        coords={
            "time": pd.date_range("2070-01-01", periods=n),
            "lat": np.array([1.0, 2.0]),
            "lon": np.array([1.0, 2.0]),
            "spatial_ref": 0,
        },
        attrs={"crs": 4326, "category": "meteo"},
    )


def test_wg4_synthetic_pass():
    assert ic.validate_wg4(_wg4_good()) == []


def test_wg4_synthetic_fail():
    ds = _wg4_good().drop_vars("precip")  # missing a required variable
    assert ic.validate_wg4(ds) != []


def test_wg4_crs_category_absent_is_ok():
    """Empty global attrs must PASS — the real artifact's actual shape.

    Corrected 2026-07-25 on the first --notemp capture: the generator NC carries
    no global attrs at all. Its CRS lives in the spatial_ref coord (CF/rioxarray)
    and crs/category are catalog metadata that validate_wg5 pins. Requiring them
    here asserted the right values on the wrong surface.
    """
    ds = _wg4_good()
    ds.attrs = {}
    assert ic.validate_wg4(ds) == []


@pytest.mark.parametrize(
    "attrs",
    [
        {"crs": 3857},                          # contradictory crs
        {"category": "hydro"},                   # contradictory category
        {"crs": 4326, "category": "hydro"},      # one right, one wrong
    ],
)
def test_wg4_contradictory_crs_category_still_fails(attrs):
    """Asserted-if-present keeps its teeth: a PRESENT wrong value is a violation."""
    ds = _wg4_good()
    ds.attrs = attrs
    assert ic.validate_wg4(ds) != []


def test_wg6_synthetic_pass():
    # WG-6 shares HM-2's contract — reuse the conforming HM-2 object.
    assert ic.validate_wg6(_hm2_good()) == []


def test_wg6_synthetic_fail():
    ds = _hm2_good().drop_vars("pet")  # missing a required forcing variable
    assert ic.validate_wg6(ds) != []


def _hm6b_good():
    import numpy as np
    import xarray as xr

    return xr.Dataset(
        {"river_h": (("latitude", "longitude"), np.zeros((2, 2)))},
        coords={
            "latitude": np.array([1.0, 2.0]),
            "longitude": np.array([1.0, 2.0]),
        },
    )


def test_hm6b_synthetic_pass():
    assert ic.validate_hm6b(_hm6b_good()) == []


def test_hm6b_synthetic_fail():
    import xarray as xr

    ds = xr.Dataset()  # no grid axes, no state variables
    assert ic.validate_hm6b(ds) != []


# ===========================================================================
# Layer 2 — real-fixture integration (skipif _FIXTURE_ABSENT)
# ===========================================================================
#
# Each case opens a persisted fixture artifact and asserts the validator's
# report is empty. The 12 continuously-verified checks: 10 per-artifact
# (WG-1,2,3,5; HM-1,2,3,4,5,7) + 2 relational (gauge-identity — parametrized
# over the 12 (toml, output_rlz) pairs; catalog-grid).


def _open_ds(path):
    import xarray as xr

    return xr.open_dataset(path)


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_wg1_integration():
    key = "era5_20000101_20201231"
    path = join(_STORE_ROOT, key, "extract_historical.nc")
    with _open_ds(path) as ds:
        assert ic.validate_wg1(ds) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_wg2_integration():
    df = pd.read_csv(_member_artifact(
        join(_WG_DIR, "_work", "st_1.csv"),
        join(_WG_DIR, "_work", "cst_1.csv"),
    ))
    assert ic.validate_wg2(df) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_wg3_integration():
    with open(join(_WG_DIR, "config", "weathergen_config.yml")) as f:
        cfg = yaml.safe_load(f)
    assert ic.validate_wg3(cfg) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_wg5_integration():
    with open(_EXP_CATALOG) as f:
        cfg = yaml.safe_load(f)
    assert ic.validate_wg5(cfg) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_wg5_catalog_grid_integration():
    with open(_EXP_CATALOG) as f:
        catalog = yaml.safe_load(f)
    with open(join(_EXP, "config", "snake_config_climate_experiment.yml")) as f:
        snap = yaml.safe_load(f)
    exp_cfg = snap["workflows"]["climate_experiment"]
    rlz_num = exp_cfg["realizations_num"]
    _, _, st_num = stress_test_grid(exp_cfg["stress_test"])
    # The catalog KEYS carry the member token, so P2's rename moves them. Same
    # pre-P2 fixture condition as `_member_artifact`, expressed on the key shape
    # rather than a path: skip only when every entry still uses the old token,
    # never on the catalog being absent or empty.
    entries = [k for k in catalog if isinstance(k, str) and k.startswith("rlz_")]
    if entries and all("_cst_" in k for k in entries):
        pytest.skip(_PRE_P2_MEMBER_TOKEN)
    assert ic.validate_wg5_catalog_grid(catalog, rlz_num, st_num) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_hm1_integration():
    with _open_ds(join(_MODEL_DIR, "staticmaps.nc")) as ds:
        assert ic.validate_hm1(ds) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_hm2_integration():
    path = join(_MODEL_DIR, "forcing", "inmaps_historical.nc")
    with _open_ds(path) as ds:
        assert ic.validate_hm2(ds) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_hm3_integration():
    import geopandas as gpd

    geoms = join(_MODEL_DIR, "staticgeoms")
    region = gpd.read_file(join(geoms, "region.geojson"))
    outlets = gpd.read_file(join(geoms, "outlets.geojson"))
    outlet_index = pd.read_csv(join(geoms, "outlet_index.csv"))
    assert ic.validate_hm3(region, outlets, outlet_index) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_hm4_integration():
    import tomllib

    with open(join(_MODEL_DIR, "wflow_sbm.toml"), "rb") as f:
        base = tomllib.load(f)
    assert ic.validate_hm4(base) == []
    with open(_member_artifact(
        join(_RUNS_DIR, "config", "rlz_1_st_1.toml"),
        join(_RUNS_DIR, "config", "rlz_1_cst_1.toml"),
    ), "rb") as f:
        per_member = tomllib.load(f)
    assert ic.validate_hm4(per_member) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_hm5_integration():
    # wf1 output.csv + a wf3 per-member run csv — both persist.
    wf1 = pd.read_csv(join(_MODEL_DIR, "run_default", "output.csv"))
    assert ic.validate_hm5(wf1) == []
    wf3 = pd.read_csv(_member_artifact(
        join(_RUNS_DIR, "output", "rlz_1_st_1.csv"),
        join(_RUNS_DIR, "output", "rlz_1_cst_1.csv"),
    ))
    assert ic.validate_hm5(wf3) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_hm7_integration():
    # The seed config declares `wflow_outvars: ["river discharge"]`, so the
    # experiment emits exactly one indicator table. R11 CR-2 replaced
    # basin_indicators.csv with per-variable tables; there is no basin variable
    # in the seed, so none is expected.
    q = pd.read_csv(join(_EXP, "results", "q_indicators.csv"))
    # The fixture is only regenerated when WF3 re-runs, which R11 P1 does not do
    # -- P3 owns the single re-run and re-record. Skip on the PRE-R11 HEADER
    # specifically, never on the file's absence: a bare existence guard is how
    # R9-4 turned a wrong path into a silent pass, and a new-shape table that is
    # genuinely broken must still fail here.
    if list(q.columns)[:1] == ["statistic"]:
        pytest.skip(
            "fixture q_indicators.csv predates R11 CR-2 (wide shape); "
            "regenerated by P3's WF3 re-run"
        )
    assert ic.validate_hm7({"q": q}) == []


def _gauge_identity_pairs():
    """The 12 fixture (toml, output_rlz) pairs (rlz {1,2} x st {1..6})."""
    return [(n, m) for n in (1, 2) for m in range(1, 7)]


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
@pytest.mark.parametrize("rlz,st", _gauge_identity_pairs())
def test_gauge_identity_integration(rlz, st):
    import tomllib

    with open(_member_artifact(
        join(_RUNS_DIR, "config", f"rlz_{rlz}_st_{st}.toml"),
        join(_RUNS_DIR, "config", f"rlz_{rlz}_cst_{st}.toml"),
    ), "rb") as f:
        toml_cfg = tomllib.load(f)
    output_rlz = pd.read_csv(_member_artifact(
        join(_RUNS_DIR, "output", f"rlz_{rlz}_st_{st}.csv"),
        join(_RUNS_DIR, "output", f"rlz_{rlz}_cst_{st}.csv"),
    ))
    qstats = pd.read_csv(join(_EXP, "results", "q_indicators.csv"))
    # Same stale-fixture condition as test_hm7_integration, and guarded the same
    # narrow way: on the PRE-R11 HEADER, never on the file being absent.
    if list(qstats.columns)[:1] == ["statistic"]:
        pytest.skip(
            "fixture q_indicators.csv predates R11 CR-2 (wide shape); "
            "regenerated by P3's WF3 re-run"
        )
    assert ic.validate_hm_gauge_column_identity(toml_cfg, output_rlz, qstats) == []


# --- temp() content integration cases — doubly skip-guarded (commit-4) ------
#
# Each carries BOTH the fixture-absent skipif (Layer-2 convention) AND a
# temp-absent runtime skip with the documented reason, since the temp()
# artifact is deleted after its consumer finishes and is absent on the default
# fixture. The ``--notemp`` capture procedure (both seam docs' validator
# indexes) un-skips these on disk without a design change.

_TEMP_ABSENT = "temp() artifact absent; capture via --notemp"

# Fixture temp() paths (present only after a --notemp capture run). R9 P2 also
# flattened the member naming here: the rlz_<r>/ directory level dissolved and
# the index went back into the stem, so these are `inmaps_rlz_1_st_1.nc`, not
# `rlz_1/forcing/inmaps_st_1.nc`. Unlike the persisted cases above these fail
# SILENTLY when stale -- the runtime `os.path.exists` guard reads a wrong path as
# "temp artifact absent" and skips, so a stale path here is indistinguishable
# from a normal run. That is why they are derived from the same roots. R11 P2's
# `cst_` -> `st_` rename is a second reason they read absent today; unlike the
# persisted cases it needs no `_member_artifact` guard, because these skip on
# the default fixture either way.
_WG4_NC = join(_WG_DIR, "output", "rlz_1_st_1.nc")
_WG6_NC = join(_RUNS_DIR, "forcing", "inmaps_rlz_1_st_1.nc")
_HM6B_NC = join(_RUNS_DIR, "output", "outstates_rlz_1_st_1.nc")


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_wg4_integration():
    if not os.path.exists(_WG4_NC):
        pytest.skip(_TEMP_ABSENT)
    with _open_ds(_WG4_NC) as ds:
        assert ic.validate_wg4(ds) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_wg6_integration():
    if not os.path.exists(_WG6_NC):
        pytest.skip(_TEMP_ABSENT)
    with _open_ds(_WG6_NC) as ds:
        assert ic.validate_wg6(ds) == []


@pytest.mark.skipif(not _fixture_present(), reason=_FIXTURE_ABSENT)
def test_hm6b_integration():
    if not os.path.exists(_HM6B_NC):
        pytest.skip(_TEMP_ABSENT)
    with _open_ds(_HM6B_NC) as ds:
        assert ic.validate_hm6b(ds) == []
