executor: cluster-generic
latency-wait: 60
keep-going: True
keep-incomplete: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
restart-times: 1
forceall: False
max-jobs-per-second: 100
max-status-checks-per-second: 1
jobs: 14 # Max jobs per snakemake workflow (FAIR use is <= 4x60cpus) 18x4 is 72
rerun-triggers: mtime

#GROUP optimized for snakemake-executor-plugin-cluster-generic  (1.0.9)
#assuming the cwd of the snakemake workflow is the project directory
cluster-generic-submit-cmd:
  mkdir -p ./data/0-log/cluster/{name} &&
  sbatch
    --partition={resources.partition}
    --time={resources.time}
    --get-user-env
    --qos={resources.qos}sacct
    --cpus-per-task={threads}
    --job-name={name}
    --output=./data/0-log/cluster/{name}/%j_{wildcards}.log

# can also add --mailtype, --mail-user, --account etc.. or other SBATCH options

#scontrol show partition 4pcpu shows unlimited mem
default-resources:
  - partition="4vcpu"   #FOR EXAMPLE
  - qos="sbatch"        
  - time="1-00:00:00"   #DEFAULT FOR ANY JOB, MAY BE OVERRIDDEN IN RULE
  - mem_mb=32768        #32GB FOR EXAMPLE, equal to total node memory

group-components:
  - run_wflow_near=4
  - run_wflow=4         #set mem_mb in rule to = (total node mem_mb / group size) to get effective grouping 
  - run_wflow_far=4
  - evaluate=4


