roots:
 - p:/i1000365-007-blue-earth/ClimateChange
 - /mnt/p/i1000365-007-blue-earth/ClimateChange
isimip3_{model}_{scenario}_{member}:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  kwargs:
    chunks:
      lat: 50
      lon: 50
      time: -1
    decode_times: true
    parallel: true
  meta:
    category: climate
    paper_doi: https://doi.org/10.5194/gmd-12-3055-2019
    paper_ref: Lange, 2019
    source_license: CC BY 4.0
    source_url: https://www.isimip.org/outputdata/
    source_version: phase3 
  placeholders:
    model: [gfdl, ipsl, mpi, mri, ukesm]
    scenario: [ssp126, ssp370, ssp585, historical]
    member: [r1i1p1f1]
  path: ISIMIP3/{model}/{scenario}/{variable}/{model}*{member}*{scenario}*{variable}_global_daily*.nc
  rename:
    pr: precip
    tas: temp
  unit_add:
    temp: -273.15
  unit_mult:
    precip: 86400
    
cmip5_{model}_historical_{member}:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  kwargs:
    chunks:
      lat: 125
      lon: 120
      time: 100
    drop_variables: ['time_bnds', 'lat_bnds', 'lon_bnds', 'height', 'average_DT']
    decode_times: true
    parallel: true
    combine: by_coords
    preprocess: to_datetimeindex
    compat: override
    coords: minimal
  meta:
    category: climate
    paper_doi: 10.1175/BAMS-D-11-00094.1
    paper_ref: Taylor et al. 2012
    source_license: todo
    source_url: https://esgf-node.llnl.gov/projects/esgf-llnl/
    source_version: 1.3.1  
  placeholders:
    model: ['ACCESS1-0', 'ACCESS1-3', 'BNU-ESM', 'CCSM4', 'CESM1-BGC',
       'CESM1-CAM5', 'CESM1-FASTCHEM', 'CESM1-WACCM', 'CMCC-CESM',
       'CMCC-CM', 'CMCC-CMS', 'CNRM-CM5', 'CNRM-CM5-2', 'CSIRO-Mk3-6-0',
       'CanCM4', 'CanESM2', 'EC-EARTH', 'FGOALS-g2', 'FIO-ESM',
       'GFDL-CM2p1', 'GFDL-CM3', 'GFDL-ESM2G', 'GFDL-ESM2M', 'GISS-E2-H',
       'GISS-E2-H-CC', 'GISS-E2-R', 'GISS-E2-R-CC', 'HadCM3',
       'HadGEM2-AO', 'HadGEM2-CC', 'HadGEM2-ES', 'IPSL-CM5A-LR',
       'IPSL-CM5A-MR', 'IPSL-CM5B-LR', 'MIROC-ESM', 'MIROC-ESM-CHEM',
       'MIROC4h', 'MIROC5', 'MPI-ESM-LR', 'MPI-ESM-MR', 'MPI-ESM-P',
       'MRI-CGCM3', 'MRI-ESM1', 'NorESM1-M', 'NorESM1-ME', 'bcc-csm1-1',
       'bcc-csm1-1-m', 'inmcm4']
    member: [r1i1p1]
  path: p:/i1000365-007-blue-earth/ClimateChange/hydromt/CMIP5/month/historical/{model}/{variable}/{variable}_*{model}_*historical_{member}*.nc
  rename:
    pr: precip
    tas: temp
    tasmin: temp_min
    tasmax: temp_max
  unit_add:
    temp: -273.15
    temp_min: -273.15
    temp_max: -273.15
  unit_mult:
    precip: 86400
    
cmip5_{model}_rcp26_{member}:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  kwargs:
    chunks:
      lat: 125
      lon: 120
      time: 50
    drop_variables: ['time_bnds', 'lat_bnds', 'lon_bnds', 'height', 'average_DT']
    decode_times: true
    parallel: true
    combine: by_coords
    preprocess: to_datetimeindex
    compat: override
    coords: minimal
  meta:
    category: climate
    paper_doi: 10.1175/BAMS-D-11-00094.1
    paper_ref: Taylor et al. 2012
    source_license: todo
    source_url: https://esgf-node.llnl.gov/projects/esgf-llnl/
    source_version: 1.3.1  
  placeholders:
    model: ['BNU-ESM', 'CCSM4', 'CESM1-CAM5', 'CNRM-CM5', 'CSIRO-Mk3-6-0',
       'CanESM2', 'FGOALS-g2', 'FIO-ESM', 'GFDL-CM3', 'GFDL-ESM2G',
       'GISS-E2-H', 'GISS-E2-R', 'HadGEM2-AO', 'HadGEM2-ES', 'IPSL-CM5A-LR',
       'IPSL-CM5A-MR', 'MIROC-ESM', 'MIROC-ESM-CHEM',
       'MIROC5', 'MPI-ESM-LR', 'MPI-ESM-MR', 'MRI-CGCM3', 'NorESM1-M',
       'NorESM1-ME', 'bcc-csm1-1', 'bcc-csm1-1-m']
    member: [r1i1p1]
  path: p:/i1000365-007-blue-earth/ClimateChange/hydromt/CMIP5/month/rcp26/{model}/{variable}/{variable}_*{model}_*rcp26_{member}*.nc
  rename:
    pr: precip
    tas: temp
    tasmin: temp_min
    tasmax: temp_max
  unit_add:
    temp: -273.15
    temp_min: -273.15
    temp_max: -273.15
  unit_mult:
    precip: 86400
    
cmip5_{model}_rcp45_{member}:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  kwargs:
    chunks:
      lat: 125
      lon: 120
      time: 50
    drop_variables: ['time_bnds', 'lat_bnds', 'lon_bnds', 'height', 'average_DT']
    decode_times: true
    parallel: true
    combine: by_coords
    preprocess: to_datetimeindex
    compat: override
    coords: minimal
  meta:
    category: climate
    paper_doi: 10.1175/BAMS-D-11-00094.1
    paper_ref: Taylor et al. 2012
    source_license: todo
    source_url: https://esgf-node.llnl.gov/projects/esgf-llnl/
    source_version: 1.3.1  
  placeholders:
    model: ['ACCESS1-0', 'ACCESS1-3', 'BNU-ESM', 'CCSM4', 'CESM1-BGC',
       'CESM1-CAM5', 'CMCC-CM', 'CMCC-CMS', 'CNRM-CM5', 'CSIRO-Mk3-6-0',
       'CanCM4', 'CanESM2', 'FGOALS-g2', 'FIO-ESM', 'GFDL-CM2p1',
       'GFDL-CM3', 'GFDL-ESM2G', 'GFDL-ESM2M', 'GISS-E2-H',
       'GISS-E2-H-CC', 'GISS-E2-R', 'GISS-E2-R-CC', 'HadCM3',
       'HadGEM2-AO', 'HadGEM2-CC', 'HadGEM2-ES', 'IPSL-CM5A-LR',
       'IPSL-CM5A-MR', 'IPSL-CM5B-LR', 'MIROC-ESM', 'MIROC-ESM-CHEM',
       'MIROC4h', 'MIROC5', 'MPI-ESM-LR', 'MPI-ESM-MR', 'MRI-CGCM3',
       'NorESM1-M', 'NorESM1-ME', 'bcc-csm1-1', 'bcc-csm1-1-m', 'inmcm4']
    member: [r1i1p1]
  path: p:/i1000365-007-blue-earth/ClimateChange/hydromt/CMIP5/month/rcp45/{model}/{variable}/{variable}_*{model}_*rcp45_{member}*.nc
  rename:
    pr: precip
    tas: temp
    tasmin: temp_min
    tasmax: temp_max
  unit_add:
    temp: -273.15
    temp_min: -273.15
    temp_max: -273.15
  unit_mult:
    precip: 86400
    
cmip5_{model}_rcp60_{member}:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  kwargs:
    chunks:
      lat: 125
      lon: 120
      time: 50
    drop_variables: ['time_bnds', 'lat_bnds', 'lon_bnds', 'height', 'average_DT']
    decode_times: true
    parallel: true
    combine: by_coords
    preprocess: to_datetimeindex
    compat: override
    coords: minimal
  meta:
    category: climate
    paper_doi: 10.1175/BAMS-D-11-00094.1
    paper_ref: Taylor et al. 2012
    source_license: todo
    source_url: https://esgf-node.llnl.gov/projects/esgf-llnl/
    source_version: 1.3.1  
  placeholders:
    model: ['CCSM4', 'CESM1-CAM5', 'CSIRO-Mk3-6-0', 'FIO-ESM', 'GFDL-CM3',
       'GFDL-ESM2G', 'GFDL-ESM2M', 'GISS-E2-H', 'GISS-E2-R', 'HadGEM2-AO',
       'HadGEM2-ES', 'IPSL-CM5A-MR', 'IPSL-CM5A-LR', 'MIROC-ESM',
       'MIROC-ESM-CHEM', 'MIROC5', 'MRI-CGCM3', 'NorESM1-M', 'NorESM1-ME',
       'bcc-csm1-1', 'bcc-csm1-1-m']
    member: [r1i1p1]
  path: p:/i1000365-007-blue-earth/ClimateChange/hydromt/CMIP5/month/rcp60/{model}/{variable}/{variable}_*{model}_*rcp60_{member}*.nc
  rename:
    pr: precip
    tas: temp
    tasmin: temp_min
    tasmax: temp_max
  unit_add:
    temp: -273.15
    temp_min: -273.15
    temp_max: -273.15
  unit_mult:
    precip: 86400
    
cmip5_{model}_rcp85_{member}:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  kwargs:
    chunks:
      lat: 125
      lon: 120
      time: 50
    drop_variables: ['time_bnds', 'lat_bnds', 'lon_bnds', 'height', 'average_DT']
    decode_times: true
    parallel: true
    combine: by_coords
    preprocess: to_datetimeindex
    compat: override
    coords: minimal
  meta:
    category: climate
    paper_doi: 10.1175/BAMS-D-11-00094.1
    paper_ref: Taylor et al. 2012
    source_license: todo
    source_url: https://esgf-node.llnl.gov/projects/esgf-llnl/
    source_version: 1.3.1  
  placeholders:
    model: ['ACCESS1-0', 'ACCESS1-3', 'BNU-ESM', 'CCSM4', 'CESM1-BGC',
       'CESM1-CAM5', 'CMCC-CESM', 'CMCC-CM', 'CMCC-CMS', 'CNRM-CM5',
       'CSIRO-Mk3-6-0', 'CanESM2', 'EC-EARTH', 'FGOALS-g2', 'FIO-ESM',
       'GFDL-CM3', 'GFDL-ESM2G', 'GFDL-ESM2M', 'GISS-E2-H', 'GISS-E2-R',
       'HadGEM2-AO', 'HadGEM2-CC', 'HadGEM2-ES', 'IPSL-CM5A-LR',
       'IPSL-CM5A-MR', 'IPSL-CM5B-LR', 'MIROC-ESM', 'MIROC-ESM-CHEM',
       'MIROC5', 'MPI-ESM-LR', 'MPI-ESM-MR', 'MRI-CGCM3', 'NorESM1-M',
       'NorESM1-ME', 'SP-CCSM4', 'bcc-csm1-1', 'bcc-csm1-1-m', 'inmcm4']
    member: [r1i1p1]
  path: p:/i1000365-007-blue-earth/ClimateChange/hydromt/CMIP5/month/rcp85/{model}/{variable}/{variable}_*{model}_*rcp85_{member}*.nc
  rename:
    pr: precip
    tas: temp
    tasmin: temp_min
    tasmax: temp_max
  unit_add:
    temp: -273.15
    temp_min: -273.15
    temp_max: -273.15
  unit_mult:
    precip: 86400