
###########################################################################################
#################################### General settings ######################################

# Path to where the wflow model will be stored (include the project name)
# test data from gabon
project_name: test
project_dir: examples/test

# Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other)
data_sources: config/deltares_data.yml
# Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other)
data_sources_climate: config/deltares_data_climate_projections.yml

# Info on the historical climate data is used in the historic model run + reference data for the weather generator
# Time horizon of the historical period
starttime: "2000-01-01T00:00:00"
endtime: "2020-12-31T00:00:00"

# Historical climate data source (name as available in the data_sources catalog file). Either [era5, chirps_global, chirps, eobs].
clim_historical: era5

# List of wflow output variables to save
wflow_outvars: ['river discharge', 'overland flow', 'actual evapotranspiration', 'groundwater recharge', 'snow']

###########################################################################################
#################################### Model building #######################################

# hydromt "region" for building the model, coordinates are in EPSG 4326
# for more info on how to fill this, you can see the hydromt documentation: 
# https://deltares.github.io/hydromt/latest/user_guide/cli.html#region-options
# For wflow please use either 'basin' or 'subbasin' keywords
model_region: "{'subbasin': [9.666, 0.4476], 'strord': 5}"
# Grid resolution of the model in degrees
model_resolution: 0.0062475

# If available, please here put the path to the available observation stations locations files
# csv file containing three columns: station_ID, x, y
output_locations: "data/observations/output-locations-test.csv" # If set to None, will default to the wflow outlets
# Path to the file with observed discharge timeseries per station 
observations_timeseries: "data/observations/observations_timeseries_test.csv" 

###########################################################################################
################################## Climate projections ####################################
# climate models and scenarios
clim_project: cmip5
models: ['MIROC5', 'HadGEM2-ES', 'IPSL-CM5A-LR', 'CMCC-CM', 'CNRM-CM5', 'GFDL-ESM2M']
scenarios: [rcp45, rcp85]
members: [r1i1p1]

variables: [precip, temp, temp_min, temp_max]

# time horizons of the climate projections
start_month_hyd_year: Jan
historical: 1960, 2000
future_horizons: 
  near: 2020, 2060
  far: 2060, 2100

# Additional gridded outputs (else only basin average)
save_grids: FALSE

###########################################################################################
################################## Stress Test Experiment #################################

# Name of the experiment
experiment_name: experiment_01      
# Number of climate realizations
realizations_num: 2
# Future Time horizon for the climate experiment
starttime_climate: 2030

# Climate stress test parameters
# Temperature change factors
# including number of steps and min, max change
temp:
  step_num: 1
  transient_change: TRUE
  # Monthly coefficients to set the minimum and maximum bounds of mean temp changes
  mean:  
    min: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    max: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0] 

# Precipitation change factors
# including number of steps and min, max change
precip:
  step_num: 2
  transient_change: TRUE
  # Monthly coefficients to set the minimum and maximum bounds of mean precip changes
  mean:
    min: [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7] 
    max: [1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3]
  # Monthly coefficients to set the minimum and maximum bounds of precip variability
  variance:
    min: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    max: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
