# Path to where the wflow model will be stored (include the project name)
project_name: Gabon
project_dir: examples/Gabon

# Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other)
data_sources: config/deltares_data_climate_projections.yml

# climate models and scenarios
clim_project: isimip3
models: [gfdl]
scenarios: [ssp370]

# time horizons
start_month_hyd_year: Oct
historical: 1991-01-01, 2014-12-31
future_horizons: 
  near: 2021-01-01, 2050-12-31
  far: 2071-01-01, 2100-12-31



