### General setting ###
# Path to where the wflow model will be stored (include the project name)
project_name: Gabon
project_dir: examples/Gabon

# Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other)
data_sources: config/deltares_data.yml

# Time horizon
starttime: "2000-01-01T00:00:00"
endtime: "2020-12-31T00:00:00"

### Model building ###
# hydromt "region" for building the model
model_region: "{'subbasin': [9.666, 0.4476], 'strord': 5}"
model_resolution: 0.0062475

# name of the files wihtout project name suffix
output_locations: "config/output-locations-Gabon.csv" # If set to None, will default to the wflow outlets
observations_timeseries: "data/observations/observations_timeseries_Gabon.csv" 

### Climate experiment ###
experiment_name: experiment_01
# Number of climate realizations
realizations_num: 3
# Number of stress tests (temp*precip steps)
#stresstests_num: 6
# Time horizon for the climate experiment
starttime_climate: "2030-01-01T00:00:00"
endtime_climate: "2050-12-31T00:00:00"

# Stress test definition
########## Temperature change factors ##########
temp:
  step_num: 2
  change_type: transient
  mean:
    min:
      - 0.0  # January
      - 0.0  # February
      - 0.0  # March
      - 0.0  # April
      - 0.0  # May
      - 0.0  # June
      - 0.0  # July
      - 0.0  # August
      - 0.0  # September
      - 0.0  # October
      - 0.0  # November
      - 0.0  # December
    max:
      - 3.0  # January
      - 3.0  # February
      - 3.0  # March
      - 3.0  # April
      - 3.0  # May
      - 3.0  # June
      - 3.0  # July
      - 3.0  # August
      - 3.0  # September
      - 3.0  # October
      - 3.0  # November
      - 3.0  # December

########## #Precipitation change factors ##########
precip:
  step_num: 3
  change_type: transient
  mean:
    min:
      - 0.7  # January
      - 0.7  # February
      - 0.7  # March
      - 0.7  # April
      - 0.7  # May
      - 0.7  # June
      - 0.7  # July
      - 0.7  # August
      - 0.7  # September
      - 0.7  # October
      - 0.7  # November
      - 0.7  # December
    max:
      - 1.3  # January
      - 1.3  # February
      - 1.3  # March
      - 1.3  # April
      - 1.3  # May
      - 1.3  # June
      - 1.3  # July
      - 1.3  # August
      - 1.3  # September
      - 1.3  # October
      - 1.3  # November
      - 1.3  # December
  variance:
    min:
      - 1.0  # January
      - 1.0  # February
      - 1.0  # March
      - 1.0  # April
      - 1.0  # May
      - 1.0  # June
      - 1.0  # July
      - 1.0  # August
      - 1.0  # September
      - 1.0  # October
      - 1.0  # November
      - 1.0  # December
    max:
      - 1.0  # January
      - 1.0  # February
      - 1.0  # March
      - 1.0  # April
      - 1.0  # May
      - 1.0  # June
      - 1.0  # July
      - 1.0  # August
      - 1.0  # September
      - 1.0  # October
      - 1.0  # November
      - 1.0  # December
