
###########################################################################################
#################################### General settings ######################################

# Path to where the wflow model will be stored (include the project name)
project_name: Vakhsh_Afghanistan
project_dir: c:\Users\strien\MyProjects\2024_CST\Vakhsh_chirps


# Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other)
data_sources: config/deltares_data.yml
# Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other)
#data_sources_climate: config/deltares_data_climate_projections.yml
data_sources_climate: config/cmip6_data.yml
# Info on the historical climate data is used in the historic model run + reference data for the weather generator
# Time horizon of the historical period
starttime: "2000-01-01T00:00:00"
endtime: "2020-12-31T00:00:00"

# Historical climate data source (name as available in the data_sources catalog file). Either [era5, chirps_global, chirps, eobs].
clim_historical: chirps_global

# List of wflow output variables to save
wflow_outvars: ['river discharge', 'precipitation', 'overland flow', 'actual evapotranspiration', 'groundwater recharge']

###########################################################################################
#################################### Model building #######################################

# hydromt "region" for building the model, coordinates are in EPSG 4326
# for more info on how to fill this, you can see the hydromt documentation: 
# https://deltares.github.io/hydromt/latest/user_guide/cli.html#region-options
# For wflow please use either 'basin' or 'subbasin' keywords
model_region: "{'subbasin': [68.299808, 37.12327], 'uparea':30}" 

# Grid resolution of the model in degrees
# 0.008333 = 1 kms
# 0.016666 = 2 km
# 0.0208325 = 2.5 km
# 0.024999 = 3 km
# 0.041665 = 5 km

model_resolution: 0.041665
# Path to model build configuration
model_build_config: "config/wflow_build_model.yml"

# If available, please here put the path to the available observation stations locations files
# csv file containing three columns: station_ID, x, y
output_locations: "data/observations/output-locations-vakhsh-afghanistan.csv"  # None
# Path to the file with observed discharge timeseries per station 
observations_timeseries: None

###########################################################################################
################################## Climate projections ####################################
# climate models and scenarios
clim_project: cmip6
models: ['IPSL/IPSL-CM6A-LR','SNU/SAM0-UNICON','NCAR/CESM2','NCAR/CESM2-WACCM','INM/INM-CM4-8','INM/INM-CM5-0',
    'NOAA-GFDL/GFDL-ESM4','NCC/NorESM2-LM','NIMS-KMA/KACE-1-0-G','CAS/FGOALS-f3-L','CSIRO-ARCCSS/ACCESS-CM2',
    'NCC/NorESM2-MM','CSIRO/ACCESS-ESM1-5','NCAR/CESM2-WACCM-FV2','NCAR/CESM2-FV2','CMCC/CMCC-CM2-SR5',
    'AS-RCEC/TaiESM1','NCC/NorCPM1','IPSL/IPSL-CM5A2-INCA','CMCC/CMCC-CM2-HR4','CMCC/CMCC-ESM2','IPSL/IPSL-CM6A-LR-INCA',
    'E3SM-Project/E3SM-1-0']

scenarios: [ssp126, ssp245, ssp370, ssp585]
members: [r1i1p1f1]

variables: [precip, temp]

# time horizons of the climate projections
start_month_hyd_year: Jan
historical: 1980, 2010
future_horizons: 
  near: 2040, 2060
  far: 2080, 2100

# Additional gridded outputs (else only basin average)
save_grids: FALSE

###########################################################################################
################################## Stress Test Experiment #################################

# Name of the experiment
experiment_name: experiment
# Number of climate realizations
realizations_num: 3
# Future Time horizon for the climate experiment
horizontime_climate: 2050
# Length of future run in years
run_length: 20
# Run historical realization
run_historical: FALSE

# Climate stress test parameters
# Temperature change factors
# including number of steps and min, max change
temp:
  step_num: 2
  transient_change: TRUE
  # Monthly coefficients to set the minimum and maximum bounds of mean temp changes
  mean:  
    min: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    max: [9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0] 

# Precipitation change factors
# including number of steps and min, max change
precip:
  step_num: 4
  transient_change: FALSE
  # Monthly coefficients to set the minimum and maximum bounds of mean precip changes
  mean:
    min: [0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50] 
    max: [1.50, 1.50, 1.50, 1.50, 1.50, 1.50, 1.50, 1.50, 1.50, 1.50, 1.50, 1.50]
  # Monthly coefficients to set the minimum and maximum bounds of precip variability
  variance:
    min: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    max: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

# Runoff statistics
# Drought return period
Tlow: 2
# Flood return period
Tpeak: 10
# Aggregate realizations before computing statistics
aggregate_rlz: TRUE