# Path to where the wflow model will be stored (include the project name)
project_name: Gabon
project_dir: examples/Gabon

# Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other)
data_sources: config/deltares_data_climate_projections.yml

# climate models and scenarios
clim_project: cmip5
models: ['MIROC5']
scenarios: [rcp45, rcp85]
members: [r1i1p1]

variables: [precip, temp, temp_min, temp_max]

# time horizons
start_month_hyd_year: Jan
historical: 1960, 2000
future_horizons: 
  near: 2020, 2060



