
Description: >
  This yml file includes general parameters to configure the weather generator.

general:
  variables:
      - precip
      - temp
      - temp_min
      - temp_max

generateWeatherSeries:
  month.start: 1
  warm.variable: precip
  warm.subset.criteria: NULL
  mc.wet.quantile: 0.2
  mc.extreme.quantile: 0.8
  evaluate.model: TRUE
  evaluate.grid.num: 20
  compute.parallel: FALSE
  seed: 123
  dry.spell.change: 1,1,1,1,1,1,1,1,1,1,1,1
  wet.spell.change: 1,1,1,1,1,1,1,1,1,1,1,1
