setup_reservoirs:
  reservoirs_fn: hydro_reservoirs  # source for reservoirs based on GRAND: {hydro_reservoirs}; None to skip
  min_area: 1.0           # minimum lake area to consider [km2]
  timeseries_fn: jrc # if 'jrc' or 'gww' is used to calculate some reservoir attributes instead of the GRanD and HydroLAKES db.   

setup_lakes:
  lakes_fn: hydro_lakes   # source for lakes based on hydroLAKES: {hydro_lakes}; None to skip
  min_area: 10.0          # minimum reservoir area to consider [km2]

setup_glaciers:
  glaciers_fn: rgi           # source for glaciers based on Randolph Glacier Inventory {rgi}; None to skip
  min_area: 1.0           # minimum glacier area to consider [km2]