read_config: # read user-defined config template in build mode instead of the default
  config_fn: "./wflow_sbm.toml"

setup_basemaps:
  hydrography_fn: merit_hydro_ihu   # source hydrography data {merit_hydro, merit_hydro_1k}
  basin_index_fn: merit_hydro_index # source of basin index corresponding to hydrography_fn
  upscale_method: ihu           # upscaling method for flow direction data, by default 'ihu'

setup_rivers:
  hydrography_fn: merit_hydro_ihu   # source hydrography data, should match basemaps source
  river_geom_fn: rivers_lin2019_v1 # river source data with river width and bankfull discharge
  river_upa: 32            # minimum upstream area threshold for the river map [km2]
  slope_len: 2000          # length over which tp calculate river slope [m]
  rivdph_method: powlaw           # method to estimate depth {'powlaw', 'manning', 'gvf'}
  min_rivdph: 0.5                # minimum river depth [m]
  min_rivwth: 30               # minimum river width [m]
  smooth_len: 5000             # length over which to smooth river depth and river width [m]

setup_lulcmaps:
  lulc_fn: vito     # source for lulc maps: {globcover, vito, corine}

setup_laimaps:
  lai_fn: modis_lai     # source for LAI: {modis_lai}

setup_soilmaps:
  soil_fn: soilgrids     # source for soilmaps: {soilgrids}
  ptf_ksatver: brakensiek    # pedotransfer function to calculate hydraulic conductivity: {brakensiek, cosby}

setup_constant_pars:
  KsatHorFrac: 100
  Cfmax: 3.75653
  cf_soil: 0.038
  EoverR: 0.11
  InfiltCapPath: 5
  InfiltCapSoil: 600 
  MaxLeakage: 0
  rootdistpar: -500
  TT: 0
  TTI: 2
  TTM: 0
  WHC: 0.1
  G_Cfmax: 5.3
  G_SIfrac: 0.002
  G_TT: 1.3