
###########################################################################################
#################################### General setting ######################################

# Path to where the wflow model will be stored (include the project name)
project_dir: examples/Gabon

# Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other)
data_sources: config/deltares_data_linux.yml
# # Path to the data catalog to use (can be different for Linux/Windows/data stored on P drive or other) TODO: REMOVE
# data_sources_climate: config/deltares_data_climate_projections_linux.yml
data_sources_climate: config/cmip6_data.yml

# Info on the historical climate data is used in the historic model run + reference data for the weather generator
# Time horizon of the historical period
starttime: "2000-01-01T00:00:00"
endtime: "2020-12-31T00:00:00"

# List of wflow output variables to save
wflow_outvars: ['river discharge', 'precipitation', 'overland flow', 'actual evapotranspiration', 'groundwater recharge', 'snow']

###########################################################################################
#################################### Model building #######################################

# hydromt "region" for building the model, coordinates are in EPSG 4326
# for more info on how to fill this, you can see the hydromt documentation: 
# https://deltares.github.io/hydromt/latest/user_guide/cli.html#region-options
# For wflow please use either 'basin' or 'subbasin' keywords
model_region: "{'subbasin': [9.666, 0.4476], 'uparea': 100}"
# Grid resolution of the model in degrees
model_resolution: 0.0062475
# Path to model build configuration
model_build_config: "config/cst_api/wflow_build_model.yml"
waterbodies_config: "config/cst_api/wflow_update_waterbodies.yml"

# Options to prepare wflow forcing for different data sources
forcing_options:
  era5: # clim/precip source name
    precip_fn: era5 # data source for precipitation
    temp_pet_fn: era5 # data source for temperature and pet if computed
    dem_forcing_fn: era5_orography # data source for orography for downscaling temperature
    pet_method: debruin # method to compute pet
    press_correction: true
    color: blue

# If available, please here put the path to the available observation stations locations files
# csv file containing three columns: station_ID, x, y
output_locations: "data/observations/output-locations-test.csv" # If set to None, will default to the wflow outlets
# Path to the file with observed discharge timeseries per station 
observations_timeseries: "data/observations/observations_timeseries_test.csv" 

###########################################################################################
################################## Climate projections ####################################
# climate models and scenarios
clim_project: cmip6
#models: ['NOAA-GFDL/GFDL-ESM4', 'INM/INM-CM4-8' ,'INM/INM-CM5-0','NIMS-KMA/KACE-1-0-G','NCC/NorESM2-MM','NCC/NorESM2-LM','CMCC/CMCC-CM2-SR5','CMCC/CMCC-ESM2']
models: ['NOAA-GFDL/GFDL-ESM4', 'CMCC/CMCC-ESM2', 'INM/INM-CM5-0']
#scenarios: [ssp126, ssp245, ssp370, ssp585]
scenarios: [ssp245, ssp585]
members: [r1i1p1f1]

variables: [precip, temp]

# time horizons of the climate projections
start_month_hyd_year: Jan
historical: 1980, 2010
future_horizons:
  near: 2030, 2060
  far: 2070, 2100

# Additional gridded outputs (else only basin average)
save_grids: FALSE

###########################################################################################
################################## Climate experiment #####################################
# Reference historical climate to use for the stress test
clim_reference: era5
# Weather generator default/advanced settings file
weathergen_config: config/cst_api/weathergen_config.yml
# Name of the experiment
experiment_name: experiment
# Number of climate realizations
realizations_num: 2
# Future Time horizon for the climate experiment
horizontime_climate: 2050
# Length of future run in years
run_length: 20
# Run historical realization
run_historical: FALSE

# Climate stress test parameters
# Temperature change factors
# including number of steps and min, max change
temp:
  step_num: 1
  transient_change: TRUE
  # Monthly coefficients to set the minimum and maximum bounds of mean temp changes
  mean:  
    min: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    max: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0] 

# Precipitation change factors
# including number of steps and min, max change
precip:
  step_num: 2
  transient_change: TRUE
  # Monthly coefficients to set the minimum and maximum bounds of mean precip changes
  mean:
    min: [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7] 
    max: [1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3]
  # Monthly coefficients to set the minimum and maximum bounds of precip variability
  variance:
    min: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    max: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

# Drought return period
Tlow: 2
# Flood return period
Tpeak: 10
# Aggregate realizations before computing statistics
aggregate_rlz: TRUE