name: blueearth-cst

channels:
  - conda-forge

dependencies:
  - cartopy
  - datrie # for snakemake
  - dvc
  - descartes
  - flit>=3.2
  - gcsfs
  - gdal>=3.1
  - geopandas>=0.10
  - graphviz # for snakemake
  - hydromt>=0.7
  - jupyter # to run examples
  - matplotlib
  - numpy
  - pandas=
  - pip
  - python>=3.7
  - rasterio
  - requests
  - rioxarray
  - scipy
  - seaborn # plot
  - shapely>=2.0.0
  - tabulate==0.8.10 # snakemake dependency, bug in v0.9.0
  - xarray
  - zarr
  - pip:
    - hydroengine
    - snakemake==7.8.0
    - git+https://github.com/Deltares/hydromt_wflow.git